[package]
name = "runn"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
core-lib = { package = "core", path = "../core" }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
